version: "3"
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg11
        restart: always
        environment:
            POSTGRES_DB: "smart_dep"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
        volumes:
        - ./volumes/timescaleDB:/var/lib/posgresql/data
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:4.20
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@domain.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "54321:80"

    rabbitmq:
        image: "rabbitmq:3-management"
        restart: always
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        ports:
            - "15672:15672" # RabbitWebInterface
            - "5672:5672"   # AMQP
            - "1883:1883"   # MQTT
        labels:
            NAME: "rabbitmq"
        volumes:
            - "./config_rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
            - "./config_rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
            #- "./config_rabbitmq/autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
