version: "3"
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg11
        restart: always
        environment:
            POSTGRES_DB: "smart_dep"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
        volumes:
            - ./volumes/timescaleDB:/var/lib/posgresql/data
        ports:
            - "5432:5432"
        logging:
            options:
                max-size: "200k"
                max-file: "10"

    pgadmin:
        image: dpage/pgadmin4:4.20
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@domain.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "54321:80"
        volumes:
            - ./config_pgadmin/servers.json:/pgadmin4/servers.json
        depends_on:
            - timescaledb
        logging:
            options:
                max-size: "200k"
                max-file: "10"

    rabbitmq:
        image: "rabbitmq:3-management"
        restart: always
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        ports:
            - "15672:15672" # RabbitWebInterface
            - "5672:5672" # AMQP
            - "1883:1883" # MQTT
        labels:
            NAME: "rabbitmq"
        volumes:
            - "./config_rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
            - "./config_rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
            #- "./config_rabbitmq/autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
        logging:
            options:
                max-size: "200k"
                max-file: "10"

    web:
        build:
            context: web-frontend
        restart: always
        # For debug
        ports:
            - "81:80"
        depends_on:
            - apiserver

    apiserver:
        build:
            context: api-server
        restart: always
        # For swagger access
        ports:
            - "5000:8080"
        depends_on:
            - timescaledb
        volumes:
            # Mapping configuration with required env (default: dev)
            - "./api-server/config/${SMART_ENV:-dev}/config.py:/app/config.py"
        logging:
            options:
                max-size: "200k"
                max-file: "10"

    emulator:
        build:
            context: emulator 
        restart: always 
        volumes: 
            - "./emulator/config.yml:/emulator/config.yml"
        depends_on:
            - rabbitmq
        logging:
            options:
                max-size: "200k"
                max-file: "10"