app:
  mqtt:
    client_id: unique_mqtt_device_id
    host: 192.168.31.90
    port: 1883
    username: rabbitmq
    password: rabbitmq

  devices:
    light_01:
      mac: "01:01:01:01:01:01"
      type: light
      place_id: 8201

    power_01:
      mac: "11:11:11:11:11:11"
      type: power
      place_id: 8201

    environment:
      mac: "F1:F1:F1:F1:F1:F1"
      type: env
      place_id: 8201
